### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by stepbrobd** [Cybergenik/hopper#10]
What are the next steps for Hopper?

**Comment by Cybergenik** [comment]
1. Update help and outputs
2. Update to cmd structure for generating binaries

**Comment by Cybergenik** [comment]
2. commit: Cybergenik@148e2175a93f4362a79aa8b8c56a679ea9d75031

**Comment by Cybergenik** [comment]
1. https://github.com/Cybergenik/hopper/commit/f60beace8b9fbfacadba8b5508aabc6cc6dcb004 ✅
